// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyComdAhQsOgdlgLsCNUeOA3rM0HcI-hJrI',
    appId: '1:199095713882:web:d01cb0d96194e12d809863',
    messagingSenderId: '199095713882',
    projectId: 'medsure-da4a2',
    authDomain: 'medsure-da4a2.firebaseapp.com',
    storageBucket: 'medsure-da4a2.firebasestorage.app',
    measurementId: 'G-LJFCLL8E66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUto2qGLU2bQww3czm5yqcudTWYIndNLw',
    appId: '1:199095713882:android:55368c0bd0daa61b809863',
    messagingSenderId: '199095713882',
    projectId: 'medsure-da4a2',
    storageBucket: 'medsure-da4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8jnlSGaDdA9RWxg4U5TfGbh5rveAzq4',
    appId: '1:199095713882:ios:29598b08daed5564809863',
    messagingSenderId: '199095713882',
    projectId: 'medsure-da4a2',
    storageBucket: 'medsure-da4a2.firebasestorage.app',
    iosBundleId: 'com.medsure.medsureFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB8jnlSGaDdA9RWxg4U5TfGbh5rveAzq4',
    appId: '1:199095713882:ios:29598b08daed5564809863',
    messagingSenderId: '199095713882',
    projectId: 'medsure-da4a2',
    storageBucket: 'medsure-da4a2.firebasestorage.app',
    iosBundleId: 'com.medsure.medsureFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyComdAhQsOgdlgLsCNUeOA3rM0HcI-hJrI',
    appId: '1:199095713882:web:9e6da172fd47fbd9809863',
    messagingSenderId: '199095713882',
    projectId: 'medsure-da4a2',
    authDomain: 'medsure-da4a2.firebaseapp.com',
    storageBucket: 'medsure-da4a2.firebasestorage.app',
    measurementId: 'G-2GW777P7X9',
  );
}
